### ISSUE TITLE
Wildbuster is not compatible with the Lands plugin.

### ISSUE THREAD

**Issue by Nashlord** [BG-Software-LLC/WildBuster#34]
### Minecraft's Version

1.20.2

### Plugin's Version

Wildbuster : 2024.1
Lands : 6.40.4

### Describe the bug

The wildbuster does not work in worlds where land claims are activated. And it puts this error in the console :
```
[10:08:52] [Timer-6/WARN]: Exception in thread "Timer-6" java.lang.NoClassDefFoundError: me/angeschossen/lands/api/role/enums/RoleSetting
[10:08:52] [Timer-6/WARN]: 	at WildBuster-2024.1.jar//com.bgsoftware.wildbuster.hooks.ClaimsProvider_Lands.canBuild(ClaimsProvider_Lands.java:23)
[10:08:52] [Timer-6/WARN]: 	at WildBuster-2024.1.jar//com.bgsoftware.wildbuster.handlers.ProvidersHandler.lambda$canBuild$1(ProvidersHandler.java:53)
[10:08:52] [Timer-6/WARN]: 	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[10:08:52] [Timer-6/WARN]: 	at java.base/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1736)
[10:08:52] [Timer-6/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[10:08:52] [Timer-6/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[10:08:52] [Timer-6/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[10:08:52] [Timer-6/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[10:08:52] [Timer-6/WARN]: 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[10:08:52] [Timer-6/WARN]: 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[10:08:52] [Timer-6/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:08:52] [Timer-6/WARN]: 	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
[10:08:52] [Timer-6/WARN]: 	at WildBuster-2024.1.jar//com.bgsoftware.wildbuster.handlers.ProvidersHandler.canBuild(ProvidersHandler.java:53)
[10:08:52] [Timer-6/WARN]: 	at WildBuster-2024.1.jar//com.bgsoftware.wildbuster.objects.WPlayerBuster.lambda$null$7(WPlayerBuster.java:243)
[10:08:52] [Timer-6/WARN]: 	at WildBuster-2024.1.jar//com.bgsoftware.wildbuster.utils.TimerUtils$1.run(TimerUtils.java:12)
[10:08:52] [Timer-6/WARN]: 	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[10:08:52] [Timer-6/WARN]: 	at java.base/java.util.TimerThread.run(Timer.java:516)
[10:08:52] [Timer-6/WARN]: Caused by: java.lang.ClassNotFoundException: me.angeschossen.lands.api.role.enums.RoleSetting
[10:08:52] [Timer-6/WARN]: 	... 17 more
```

### To Reproduce

Install the 2 plugins and try to place a wildbuster in the world where lands is activated.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs, let me know
