### ISSUE TITLE
1.21 Issues

### ISSUE THREAD

**Issue by iandrew1337** [BG-Software-LLC/WildBuster#35]
### Minecraft's Version

Purpur 1.21 (Build 2261)

### Plugin's Version

Dev Build Number 27

### Describe the bug

The plugin does not load in at all

### To Reproduce

Load the plugin into the described version

### Additional Information

```
[WildBuster]: Error initializing plugin 'WildBuster-2024.1-b27.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
java.lang.AssertionError: Missing intrusive holder for ResourceKey[minecraft:enchantment / minecraft:wildbuster_glowing_enchant]:Enchantment
at net.minecraft.core.MappedRegistry.register(MappedRegistry.java:132) ~[purpur-1.21.jar:1.21-2261-14136b8]
at net.minecraft.core.Registry.register(Registry.java:119) ~[purpur-1.21.jar:1.21-2261-14136b8]
at net.minecraft.core.Registry.register(Registry.java:115) ~[purpur-1.21.jar:1.21-2261-14136b8]
at WildBuster-2024.1-b27.jar/com.bgsoftware.wildbuster.nms.v1_21.GlowEnchantment.lambda$initializeHandle$0(GlowEnchantment.java:44) ~[WildBuster-2024.1-b27.jar:?]
at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
at WildBuster-2024.1-b27.jar/com.bgsoftware.wildbuster.nms.v1_21.GlowEnchantment.initializeHandle(GlowEnchantment.java:41) ~[WildBuster-2024.1-b27.jar:?]
at WildBuster-2024.1-b27.jar/com.bgsoftware.wildbuster.nms.v1_21.GlowEnchantment.<clinit>(GlowEnchantment.java:25) ~[WildBuster-2024.1-b27.jar:?]
at WildBuster-2024.1-b27.jar/com.bgsoftware.wildbuster.nms.v1_21.NMSAdapterImpl.getGlowEnchant(NMSAdapterImpl.java:171) ~[WildBuster-2024.1-b27.jar:?]
at WildBuster-2024.1-b27.jar/com.bgsoftware.wildbuster.nms.v1_21.NMSAdapterImpl.createGlowEnchantment(NMSAdapterImpl.java:176) ~[WildBuster-2024.1-b27.jar:?]
at WildBuster-2024.1-b27.jar/com.bgsoftware.wildbuster.WildBusterPlugin.onLoad(WildBusterPlugin.java:60) ~[WildBuster-2024.1-b27.jar:?]
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.21.jar:1.21-2261-14136b8]
at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.21.jar:1.21-2261-14136b8]
at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.21.jar:1.21-2261-14136b8]
at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[purpur-1.21.jar:1.21-2261-14136b8]
at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:549) ~[purpur-1.21.jar:1.21-2261-14136b8]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[purpur-1.21.jar:1.21-2261-14136b8]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234) ~[purpur-1.21.jar:1.21-2261-14136b8]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2261-14136b8]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue continues, let me know
