### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by skigrex** [BG-Software-LLC/WildBuster#8]
### Minecraft's Version

paper 1.17

### Plugin's Version

b11, the latest dev build

### Describe the bug

when i place a large or a normal buster it start spaming me a warn on console, it works perfectly, but it is a bit annoying

### To Reproduce

just place any buster 

### Additional Information

[16:36:58 WARN]: java.lang.IllegalArgumentException
[16:36:58 WARN]:        at jdk.internal.reflect.GeneratedConstructorAccessor125.newInstance(Unknown Source)
[16:36:58 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:36:58 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[16:36:58 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[16:36:58 WARN]:        at com.bgsoftware.wildbuster.nms.NMSAdapter_v1_17_R1.createMultiBlockChangePacket(NMSAdapter_v1_17_R1.java:136)
[16:36:58 WARN]:        at com.bgsoftware.wildbuster.nms.NMSAdapter_v1_17_R1.refreshChunk(NMSAdapter_v1_17_R1.java:102)
[16:36:58 WARN]:        at com.bgsoftware.wildbuster.utils.blocks.MultiBlockTask.lambda$submitUpdate$4(MultiBlockTask.java:91)
[16:36:58 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
[16:36:58 WARN]:        at com.bgsoftware.wildbuster.utils.blocks.MultiBlockTask.submitUpdate(MultiBlockTask.java:77)
[16:36:58 WARN]:        at com.bgsoftware.wildbuster.utils.blocks.MultiBlockTask.lambda$submitUpdate$2(MultiBlockTask.java:61)
[16:36:58 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[16:36:58 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[16:36:58 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
[16:36:58 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[16:36:58 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[16:36:58 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[16:36:58 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
